### ISSUE TITLE
Where should abstract methods go in terms of logical ordering?

### ISSUE THREAD

**Issue by erseno** [ribot/android-guidelines#17]
Hello all

First, I am very thankful to those who wrote this guide, I have been looking to improve my coding standard and have been following this and thus far found it very useful .

I have a question regarding this section

https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md#2210-class-member-ordering

Where should abstract method declarations go in relation to ordering 
For example in a base activity class

```java
public abstract class BaseActivity extends AppCompatActivity implements FragmentManager.OnBackStackChangedListener {

    public abstract String getScreenNameForAnalytics();

}

```

Thanks for reading 

Ersen

**Comment by dengit** [comment]
Follow the "Public" section?

**Comment by ivacf** [comment]
There isn't any specific rule in this guidelines about abstract methods. You can think about them as normal public method.

**Comment by erseno** [comment]
Thanks guys :)
