### ISSUE TITLE
Is it possible to inject RetrofitServie into Application instance?

### ISSUE THREAD

**Issue by thomasdola** [ribot/android-guidelines#20]
`public class RymeApplication extends Application{`
    `@Inject`
    `RymeService mRymeService;`
=>and use it `onCreate()`
possible?

**Comment by ivacf** [comment]
I'm not sure I fully understand your question. If you are asking if you can inject fields from within the Application class, the answer is yes. It works as any other class.

I don't think this question is related to these guidelines and is not an issue relevant to this repository so I'm going to close it.
