### ISSUE TITLE
ViewGroup as View.

### ISSUE THREAD

**Issue by Tooto** [ribot/android-guidelines#23]
In your picture there is a way to use ViewGroup as a MVP View.
https://github.com/ribot/android-guidelines/raw/master/architecture_guidelines/architecture_diagram.png
Is there any example how i can do it?
I want to know how i can inject presenter for such view and where attachView() and detachView() should be placed.
May i have Presenter inside my LinearLayout?

**Comment by jemmaSlater** [comment]
Hello, sorry for the delayed response!

To use a ViewGroup, the attachView() and detachView() methods would just need to be called where the ViewGroup itself gets created and destroyed - assuming you want the presenter to handle the management of the Views within this ViewGroup.

If you wish to add a presenter to each individual View (eg. LinearLayout) within the ViewGroup, you will need to attach/detach each View when you add/remove them from the ViewGroup.
