### ISSUE TITLE
What about item name in MENU files?

### ISSUE THREAD

**Issue by Yousha** [ribot/android-guidelines#24]
What about item(android:id) names in menu files?

Ex.: res/menu/activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>

<menu>
   <item android:id="@+id/HERE_IS_THE_NAME" android:title="@string/action_back"></item>
</menu>
```

?

**Comment by jemmaSlater** [comment]
Hello! Does this example answer your question? 


IDs should be prefixed with the name of the element in lowercase underscore. Menu example:

```
<menu>
    <item
        android:id="@+id/menu_done"
        android:title="Done" />
</menu>
```

Taken from this section of the guidelines: https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md#2321-id-naming
